//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp11
{
    using System;
    using System.Collections.Generic;
    
    public partial class messages
    {
        public int message_id { get; set; }
        public string message_text { get; set; }
        public Nullable<int> admin_id { get; set; }
        public Nullable<int> request_id { get; set; }
    
        public virtual admin admin { get; set; }
        public virtual requests requests { get; set; }
    }
}
